#Requires -Version 7.0
param(
    [Parameter(Mandatory=$true)][string]$TestDir,
    [Parameter()][string]$Repos = 'microsoft/vscode,PowerShell/PowerShell'
)

$PSDefaultParameterValues['*:Encoding'] = 'UTF8'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$ErrorActionPreference = 'Stop'

# =====================================================================
# create-fixture.ps1
# Purpose: generate the isolated test-dir fixture consumed by T2..T6 harnesses.
# Output layout under $TestDir:
#   .output/GitHub更新监测列表.md   (initial monitor markdown with 2 repos)
#   (NO .monitor/ - step 1 creates it dynamically, per Phase 0 constraint)
#
# Contract:
#   - The markdown must satisfy SKILL's step 2 parser:
#     * Exactly one `## 监测列表` section
#     * Exactly one fixed header row
#     * Rows have 6 columns: `# | [name](url) | gitVer | gitDate | localVer | yes/no`
#     * Contains `> 最近核对时间：...` metadata line
#     * Anchors: `## 结论`, `## 更新摘要`, `## 备注`, `## 核对方法`
#   - Local version `未安装` for one repo so `uninstalled` stats work.
#   - Default repos: microsoft/vscode (synced, no), PowerShell/PowerShell (yes)
# =====================================================================

$beijingNow = [DateTimeOffset]::UtcNow.ToOffset([TimeSpan]::FromHours(8)).ToString('yyyy-MM-dd HH:mm')
$repoList   = $Repos -split ','

# Build table rows dynamically (at least 2 required)
$repoRows = @()
$idx = 0
foreach ($r in $repoList) {
    $repo = $r.Trim()
    $owner = ($repo -split '/')[0]
    $name  = ($repo -split '/')[1]
    $idx++
    if ($idx -eq 1) {
        # First repo: local matches git -> flag = no
        $repoRows += ('| {0} | [{1}](https://github.com/{2}/releases) | v1.0.0 | 2026-01-15 | v1.0.0 | no |' -f $idx, $name, $repo)
    } else {
        # Other repos: local behind git -> flag = yes
        $repoRows += ('| {0} | [{1}](https://github.com/{2}/releases) | v1.0.0 | 2026-01-15 | 未安装 | no |' -f $idx, $name, $repo)
    }
}

$md = @"
# GitHub 项目更新监测列表

> 数据来源：GitHub 官方 API（api.github.com）`releases/latest` 接口直连
> 最近核对时间：$beijingNow（北京时间，fixture）

## 监测列表

| # | 项目名称 | GIT最新版本 | GIT更新日期 | 本地版本 | 是否更新 |
|---|---------|------------|------------------|---------|-------------|
$($repoRows -join "`n")

## 结论

- fixture initial state; auto-updated by step 5.

## 更新摘要

- fixture initial state.

## 备注

- fixture: repos = $($repoList -join ', ')

## 核对方法

fixture generated by lib/create-fixture.ps1.
"@

# Write output directory and file
$outDir = Join-Path $TestDir '.output'
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Force -Path $outDir | Out-Null }
$mdPath = Join-Path $outDir 'GitHub更新监测列表.md'

# Write as UTF-8 no BOM, LF line endings (matches production SKILL file)
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($mdPath, $md, $utf8NoBom)

$sha = (Get-FileHash -Algorithm SHA256 -Path $mdPath).Hash.ToUpper()
Write-Output "FIXTURE_WRITTEN=$mdPath"
Write-Output "FIXTURE_SHA256=$sha"
Write-Output "FIXTURE_REPOS=$Repos"
Write-Output "FIXTURE_REPO_COUNT=$($repoList.Count)"
Write-Output "FIXTURE_TESTDIR=$TestDir"

# Confirm no .monitor/ directory was created (Phase 0 constraint)
if (Test-Path (Join-Path $TestDir '.monitor')) {
    Write-Output "FIXTURE_MONITOR_DIR_EXISTS=UNEXPECTED"
    exit 3
} else {
    Write-Output "FIXTURE_MONITOR_DIR_ABSENT=YES"
}
